POST https://192.168.17.163:8787/api/questionbox/answer/new
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI2NDI4ZTc4MWNhZmJhYmQ1ZDcxN2ZmN2IiLCJSb2xlIjoiUk9MRV9BRE1JTiIsImlzcyI6InRlc3QiLCJleHAiOjE2ODQzMjQ4NDd9.cS7Fm-oMG_gXi94ak5OPEFE-h3WM9MewxepC4I0HsDo

{
    "Content": "哲学问题",
    "QuestionID": "64622227552a9928540d54aa",
    "major": {
        "id": "64368f7780b2dca238436af4",
        "name": "哲学"
    },
    "school": {
        "id": "64326d43958e16cb55f4c015",
        "name": "中国人民大学"
    }
}