POST https://127.0.0.1:8787/api/questionbox/question/new
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI2NDQwZjg2MGFjMzM4ZjFiYTAyZDZkMTYiLCJSb2xlIjoiUk9MRV9BRE1JTiIsImlzcyI6InRlc3QiLCJleHAiOjE2ODMzNjIyMDF9.t2a75T4n6lpsg4iXSgQAaXKqplojJjOgUitCZFglR5Q

{
    "title": "New Question 5",
    "description": "This is a new question",
    "major": {
        "id": "6440f79e5d0bbef01247b8dd",
        "name": "哲学"
    },
    "school": {
        "id": "",
        "name": ""
    },
    "questioner": {
        "CEEPlace": "北京",
        "Subject": "语文",
        "Age": 17,
        "Gender": "男",
        "situation": ""
    }
}