POST https://127.0.0.1:8787/api/questionbox/question/new
accept: application/json
Content-Type: application/json

{
    "title": "New Question 6",
    "description": "This is a new question",
    "major": {
        "id": "6440f79e5d0bbef01247b8dd",
        "name": "哲学"
    }
}