POST http://127.0.0.1:8787/api/questionbox/label/new
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI2NDQwZjg2MGFjMzM4ZjFiYTAyZDZkMTYiLCJSb2xlIjoiUk9MRV9BRE1JTiIsImlzcyI6InRlc3QiLCJleHAiOjE2ODQwMTM0NzZ9.yKrGiX1xOqAsyPQdehEG-gJQve2M4hsXy-SSIHpDtx8

{

}