version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: melodie_mongo
    restart: always
    ports:
      - "10200:27017"
    environment:
      - name=value
    volumes:
      - /home/hzy/data/mongo:/data
  minio:
    image: minio/minio
    container_name: melodie_minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: melodie
      MINIO_SECRET_KEY: melodie-test
    volumes:
      - /home/hzy/data/minio:/data
    ports:
      - "10100:9000"
      - "10101:9090"
    command: "server /data --console-address \":9090\" -address \":9000\" "

