version: "3.9"
services:
  postgresql:
    image: "postgres:15.2-alpine"
    container_name: melodie_postgresql
    restart: always
    environment:
      POSTGRES_DB: melodie
      # POSTGRES_ADMIN_PASSWORD: secret           #cannot use in Produce Env
      POSTGRES_USER: melodie
      POSTGRES_PASSWORD: melodie-test
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.11
    container_name: melodie_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: melodie
      RABBITMQ_DEFAULT_PASS: melodie-test
    ports:
      - "17653:8080"
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio
    container_name: melodie_minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: melodie
      MINIO_SECRET_KEY: melodie-test
    volumes:
      - /home/hzy/data/minio:/data
    ports:
      - "10100:9000"
      - "10101:9090"
    command: "server /data --console-address \":9090\" -address \":9000\" "

